---
- name: create NFS gateway directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ dir_owner }}"
    group: "{{ dir_group }}"
    mode: "{{ dir_mode }}"
  with_items:
    - /var/lib/nfs/ganesha
    - /var/run/ganesha

- name: start NFS gateway service
  service:
    name: nfs-ganesha
    state: started
    enabled: yes
